title: Kevin Liu
logo: /assets/img/sadasdasd.png
description: Genomics · Vehicle Autonomy · AI · Myrmecology
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
sass:
  sass_dir: assets/css
